language: java

#install: ant deps

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk6

script:
  - mvn compile
  - mvn package
  - mvn test
  
notifications:
  irc:
    channels:
      - "irc.pierotofy.it:6669#pierotofy.it"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true