site_name: Pizza

pages:
- Home: index.md
- Compilazione: compilazione.md
- Utilizzo: utilizzo.md
- Plugins: plugin.md
- Javadoc: javadoc.md
- Convenzioni: convenzioni.md

- About:
    - Community: pierotofy.md
    - Licenza:   license.md

theme: readthedocs
